- src/HtmlElement.php
Logic was too broad, any value that could be considered false (like '0') would be treated as an empty tag.
> Bugfix for HTML Element __toString()

- src/DocParser.php
The submitted test case failed because the parser tried to add an empty line to the already-closed IndentedCode block. In the JS reference parser, closing this block type results in it becoming a CodeBlock type, which we don't use, and therefore the addLine() logic doesn't run.  We can mirror that behavior by ensuring nothing ever calls addLine() on a closed block.
> Don't add remaining contents to closed containers (fixes #57)

- src/Block/Renderer/BlockQuoteRenderer.php
- src/Block/Renderer/ListBlockRenderer.php
- src/CommonMarkConverter.php
- src/Environment.php
- src/HtmlRenderer.php
- src/Inline/Renderer/NewlineRenderer.php
- tests/EnvironmentTest.php
> Configuration

- README.md
The JS reference implementation was moved to: https://github.com/jgm/commonmark.js, updated links accordingly.
> Update links to JS reference implementation

- CHANGELOG.md
- src/Environment.php
- src/Inline/Parser/NewlineParser.php
- src/InlineParserEngine.php
- src/Util/RegexHelper.php
We now parse long spans of non-special characters at once, vs the old approach which parsed each character individually.  This results in a whopping **50% performance boost** according to our internal benchmark (310ms to 156ms on my machine).
> Optimizations

- src/Reference/ReferenceMap.php
I would really like to have some simple way of accessing the References in the ReferenceMap without knowing the keys. I have a project where I want to display the references separately and of course there are ways to do it, but I think a
```php
$document = $parser->parse($markdown);
$references = $document->getReferenceMap()->listReferences();
```
would come in handy.
This pull request is just some proposal of the idea. I wasn't sure about naming and stuff, but it is just way too easy to implement ;)
> Adding listReferences to ReferenceMap

- .travis.yml
- CHANGELOG.md
We'll remove `allow_failures` once Travis includes the `mbstring` extension and PHP 7.0 enters a relatively-stable state (the tests work reliably well)
> Test against PHP 7.0 (nightly) but allow failures

- CHANGELOG.md
- src/Cursor.php
- src/Inline/Parser/BacktickParser.php
- src/Util/RegexHelper.php
- tests/CursorTest.php
- tests/Inline/Parser/BacktickParserTest.php
- tests/Util/RegexHelperTest.php
Issue #78 brought up an example of multi-byte support not working correctly.  It seems I made a faulty assumption that `PREG_OFFSET_CAPTURE` would return the **character** offset in multi-byte mode, which is false - it will always return the **byte** offset.
This PR fixes these issues and adds several other tests with UTF-8 strings to help ensure that UTF-8 is properly supported.
> Fix multibyte bugs

- CHANGELOG.md
- src/Inline/Parser/EmphasisParser.php
The issue was caused by non-strict tests, where a "0" string was considered falsy.
> Fix broken parsing of emphasized text ending with a '0' character (#81)

- src/Extension/MiscExtension.php
- tests/EnvironmentTest.php
The documentation implies that the main purpose of Environment::addBlockRenderer() and Environment::addInlineRenderer() are to override the default renderers ("When registering these with the environment, you must tell it which block/inline classes it should handle. This allows you to essentially “swap out” built-in renderers with your own."), and the examples suggest that it can be done like this :
```php
$environment->addBlockRenderer('FencedCode', $myRenderer);
$environment->addBlockRenderer('IndentedCode', $myRenderer);
```
The problem is this doesn't work, as you would actually have to do this in order to replace the built-in block renderers :
```php
$environment->addBlockRenderer('League\CommonMark\Block\Element\FencedCode', $myRenderer); …
```
> Allow swapping built-in renderers without using their fully qualified names

- CHANGELOG.md
- src/Block/Parser/ListParser.php
By the time parseListMarker is called, the hrule block start was already
tried. In case it matches, no further block starts are tried. So the
later check is not necessary and can be removed.
Mirrors jgm/commonmark.js#19
> Remove unnecessary check for hrule in parseListMarker

- src/DocParser.php
Seems like a typo or refactoring relict.
This should not change any public behavior or breake public APIs.
> Fix name of method argument

- .travis.yml
Avoiding the use of Travis' pre-built phar allows us to work around this
HHVM issue: https://github.com/facebook/hhvm/issues/5215
> Use locally-installed PHPUnit instead of phar; avoid coverage in HHVM

- src/Block/Element/AbstractBlock.php
The "short description" MUST be the first non-empty line in the phpdoc.
> Fixed phpdoc

- README.md
Disclaimer: I am the author of [sculpin-commonmark-bundle](https://github.com/bcremer/sculpin-commonmark-bundle).
This Sculpin Bundle provides a league/commonmark integration to [Sculpin](https://sculpin.io/).
It provides access to the low level components of league/commonmark via the sculpin DI-container.
> Add Sculpin Bundle to list of Integrations

- src/CommonMarkConverter.php
- src/Converter.php
> Added extensible converter

- src/HtmlRenderer.php
This has thrown me off a few times. Looks like a copy/paste issue. (Same exact error message can be found later in the file for invalid blocks.)
> Fix wording for invalid inline exception

- composer.json
- src/Delimiter/DelimiterStack.php
- src/Environment.php
- src/Extension/SmartPunctExtension.php
- src/Inline/Parser/CloseBracketParser.php
- src/Inline/Parser/QuoteParser.php
- src/Inline/Parser/SmartPunctParser.php
- src/Inline/Processor/EmphasisProcessor.php
- src/Inline/Processor/QuoteProcessor.php
- src/InlineParserEngine.php
- tests/functional/SmartPunctTest.php
Per jgm/commonmark.js@7bd852b40170f9a32864c6644ac7b5248f880f12
This PR implements the smart punctuation work done in commonmark.js and fixes a few bugs with this package.
- Smart quote, ellipsis, and en/em-dash replacement
- Punctuation tests added from jgm/commonmark.js
- Fix a unicode issue with parsing (see Environment.php)
- Fix bug where only a single Processor could be added (see closeBracketParser.php, EmphasisProcessor.php, and InlineParserEngine.php)
> Add smart punctuation

- src/Inline/Parser/SmartPunctParser.php
jgm/commonmark.js#58 was merged with the behavior originally proposed here. jgm/cmark has also been updated to match.
This code passes current tests and it also passes the new tests that aren't part of a commonmark.js release yet (tested manually).
> Switch behavior back to "smart" hyphen replacement per jgm/commonmark.js#58

- src/Inline/Parser/QuoteParser.php
Per jgm/commonmark.js#61, which isn't yet merged, but don't see why it wouldn't be.
This could probably be merged right away, if you wanted, since it doesn't break any existing tests. The test it helps to pass is in jgm/commonmark.js#61.
> Fix replacement of multiple apostrophes in the same paragraph

- CHANGELOG.md
- src/Block/Renderer/ListItemRenderer.php
- tests/unit/Block/Renderer/ListItemRendererTest.php
This ensures our renderer returns an HtmlElement instead of a string, which is easier to work with
> Remove unnecessary trim from ListItemRenderer

- CHANGELOG.md
- src/Block/Element/AbstractBlock.php
- src/Block/Element/BlockQuote.php
- src/Block/Element/Document.php
- src/Block/Element/HorizontalRule.php
- src/Block/Element/ListBlock.php
- src/Block/Element/ListItem.php
A default implementation is provided.  This was based on code which was duplicated across several
sub-classes.  This duplicate code is therefore unneeded and was removed.
> Make `AbstractBlock::handleRemainingContents()` no longer abstract

- .gitignore
- .travis.yml
- composer.json
This removes the need to download ocular.phar (using wget) within travis.  Also adds the ability to check the composer version constraints with (--prefer-lowest).
But all in all, follows the skeleton projects design. (https://github.com/thephpleague/skeleton)
> Update travis-ci to thephpleague's skeleton style

- composer.json
Officially, phpunit 4 does not support php 7, but 5 does.
> Also allow phpunit 5

- bin/commonmark
- src/Block/Renderer/HtmlBlockRenderer.php
- src/Environment.php
- src/Inline/Renderer/ImageRenderer.php
- src/Inline/Renderer/LinkRenderer.php
- src/Inline/Renderer/RawHtmlRenderer.php
- src/Util/ConfigurationAwareInterface.php
- src/Util/RegexHelper.php
- tests/functional/BinTest.php
- tests/functional/SafeTest.php
- tests/functional/data/safe/input.md
- tests/functional/data/safe/safe_output.html
- tests/functional/data/safe/unsafe_output.html
- tests/unit/Block/Renderer/HtmlBlockRendererTest.php
- tests/unit/Inline/Renderer/ImageRendererTest.php
- tests/unit/Inline/Renderer/LinkRendererTest.php
- tests/unit/Inline/Renderer/RawHtmlRendererTest.php
This introduces a new `safe` option for both the library and the CLI command.  Enabling it will prevent raw HTML from being rendered, as well as removing unsafe URLs in links and images.
This change mirrors https://github.com/jgm/commonmark.js/commit/57a1ae3ce97f4794f89658cd90b4e4f8d2c9d5a9
Addresses #200
> Html safe mode

- customization/inline-parsing.md
This or should be an and in order for the parser to work correctly.
> Fixed SmilieParser example

- .travis.yml
While we've always tested against PHP 7, this change will guarantee that all changes **must** be fully-supported.
This PR will be merged once Travis is using a stable build of PHP 7.
> Require PHP 7 tests to pass

- src/DocParser.php
- src/DocumentProcessorInterface.php
- src/Environment.php
- src/Extension/CommonMarkCoreExtension.php
- src/Extension/Extension.php
- src/Extension/ExtensionInterface.php
- src/Extension/MiscExtension.php
- src/Extension/SmartPunctExtension.php
- tests/unit/EnvironmentTest.php
- tests/unit/Extension/ExtensionTest.php
- tests/unit/Extension/MiscExtensionTest.php
First attempt at a document processor. I've added a basic extension which converts Twitter links to embedded tweets.
(Still WIP)
Fixes #207
> Implement document processor

- CHANGELOG.md
- src/CommonMarkConverter.php
- tests/unit/CommonMarkConverterTest.php
This change allows developers to convert Markdown using a custom environment without needing to manually instantiate the doc parser and renderer.
> Add optional `Environment` parameter to `CommonMarkConverter` constructor

- README.md
Laravel markdown has been modified to support "extensions", and alt three emoji now ships with an extension class.
> Updated alt three emoji description

- src/Environment.php
- tests/unit/EnvironmentTest.php
If an Environment creates without any inline parsers, the
`getInlineParserCharacterRegex()` method will return an invalid
regular expression. This fix ensures that a valid regex is returned
in this particular edge case.
> Fix empty inline character regex (#224)

- .styleci.yml
This fixer has been renamed: https://styleci.readme.io/docs/fixers#phpdoc_summary. Though the alias will still work, using the new name is preferred.
> Updated styleci config

- src/Converter.php
- tests/unit/ConverterTest.php
Adding Converter::__invoke as an alias to Converter::convertToHtml
to enable calling Converter object as functions
resolves #233
> Enable calling convertToHtml as a function

- composer.json
- src/Block/Element/BlockQuote.php
- src/Block/Parser/BlockQuoteParser.php
- src/Block/Parser/ListParser.php
- src/Cursor.php
- tests/functional/data/list_regressions.html
- tests/unit/CursorTest.php
These changes mirror the following upstream changes:
- https://github.com/jgm/commonmark.js/commit/b46bfd7a9a42015968e231cb16a4a634bd6e85be
- https://github.com/jgm/commonmark.js/commit/000d15df01099ff9ecd92451830083ba3f901218
- https://github.com/jgm/commonmark.js/commit/018bb6cdd029cee0066162648d8f0f3a49b7ad2e
Regression tests were updating using the latest dev-master of commonmark.js.
> Tab handling

- README.md
That way you are sure your doc is not outdated. As a user I didn't want to copy/paste that command because I'm not sure if it's up to date, and I can get the same result with a simpler command.
> Remove version constraint to let Composer figure out the best version

- src/Block/Parser/SetExtHeadingParser.php
This fix mirrors jgm/commonmark.js#109
> Allow trailing tabs in setext heading underlines

- src/Cursor.php
- src/CursorState.php
Came across this easy-win when parsing text that had an incredibly long JSON string embedded in it.
CommonMark assumes UTF8 encoding in strings and so makes use of the multi-byte `mb_` functions for string interrogation. When using character offsets, `mb_*` functions handling variable-width encodings (like UTF8) typically have to scan the string every time from the beginning which can have `O(n)` time complexity even if you're pulling out just 1 character. As such, all of the `getCharacter()` random access calls that CommonMark makes can cause the parser have `O(n^2)` running time. As CommonMark currently parses line-by-line, this becomes noticable on text with super loooonnngg lines.
For fixed-width encodings like ASCII, the `mb_*` functions can use `O(1)` pointer arithmetic. ASCII is …
> Improve Cursor performance when dealing with very long lines.

- README.md
Would you add reference to this `<sup> <sub>` extension?
https://github.com/OWS/commonmark-sup-sub-extensions
> Add reference to sup sub extensions.

- README.md
it was added via wiki convert, probably was not verified what it is:
- d35cd97fc82dc1b02e71ff5056f82db52b4f5704
currently looking at their project, seems useless project which has done only `s/commonmark/markua/g` replacement, not even bothering to remove incorrect information and correcting links.
seems waste of people time sending them there.
> readme: remove markua

- README.md
This is important feature to document, especially when migrating from other implementations.
in [cebe/markdown](https://github.com/cebe/markdown) this is documented as:
> For GithubMarkdown:
> 
> `$parser->enableNewlines = true` to convert all newlines to `<br/>`-tags. By default only newlines with two preceding spaces are converted to `<br/>`-tags.
> readme: add github enableNewlines example

- composer.json
- src/Extension/CommonMarkCoreExtension.php
- tests/unit/Block/Renderer/BlockQuoteRendererTest.php
- tests/unit/Block/Renderer/DocumentRendererTest.php
- tests/unit/Block/Renderer/FencedCodeRendererTest.php
- tests/unit/Block/Renderer/HeadingRendererTest.php
- tests/unit/Block/Renderer/HtmlBlockRendererTest.php
- tests/unit/Block/Renderer/IndentedCodeRendererTest.php
- tests/unit/Block/Renderer/ListBlockRendererTest.php
- tests/unit/Block/Renderer/ListItemRendererTest.php
- tests/unit/Block/Renderer/ParagraphRendererTest.php
- tests/unit/Block/Renderer/ThematicBreakRendererTest.php
- tests/unit/CommonMarkConverterTest.php
- tests/unit/ConverterTest.php
- tests/unit/EnvironmentTest.php
- tests/unit/Inline/Element/AbstractWebResourceTest.php
- tests/unit/Inline/Parser/BacktickParserTest.php
- tests/unit/Inline/Renderer/CodeRendererTest.php
- tests/unit/Inline/Renderer/EmphasisRendererTest.php
- tests/unit/Inline/Renderer/HtmlInlineRendererTest.php
- tests/unit/Inline/Renderer/ImageRendererTest.php
- tests/unit/Inline/Renderer/LinkRendererTest.php
- tests/unit/Inline/Renderer/NewlineRendererTest.php
- tests/unit/Inline/Renderer/StrongRendererTest.php
- tests/unit/Inline/Renderer/TextRendererTest.php
This project minimum php requirement is 5.6, so it's time to use `::class` constant.
cc @colinodell
> Use PHP 5.5 class constant

- .phpstorm.meta.php
- CHANGELOG.md
- README.md
- UPGRADE.md
- docs/0.20/basic-usage.md
- docs/0.20/customization/cursor.md
- src/Block/Parser/SetExtHeadingParser.php
- src/Context.php
- src/ContextInterface.php
- src/Cursor.php
- src/DocParser.php
We used to claim support for ISO-8859-1 encoding, and several methods hinted at us supporting other encodings like UTF-16 too.  But in reality, we were making several assumptions and optimizations that the text was UTF-8 or ASCII.  This led to issues like #361.
As a result, and because UTF-8 is overwhelming popular, we're going to drop support for all non-UTF-8-compatible encodings.  Anyone wishing to use those can still do so, they'll just need to convert to/from UTF-8 when using this library.
> Drop support for non-UTF-8-compatible encoding (fixes #361)

- CHANGELOG.md
- UPGRADE.md
- src/Delimiter/Delimiter.php
- src/Delimiter/DelimiterStack.php
- src/Delimiter/Processor/DelimiterProcessorInterface.php
- src/Delimiter/Processor/EmphasisDelimiterProcessor.php
- src/Delimiter/Processor/StaggeredDelimiterProcessor.php
- tests/functional/Delimiter/FakeDelimiterProcessor.php
- tests/functional/Delimiter/TestDelimiterProcessor.php
- tests/functional/Delimiter/UppercaseDelimiterProcessor.php
- tests/unit/Delimiter/DelimiterTest.php
This fixes a couple of type issues found in 1.0.0-beta1
> Standardize delimiter processing node types

- CHANGELOG.md
- docs/1.0/customization/event-dispatcher.md
- docs/_data/menu.yml
- src/ConfigurableEnvironmentInterface.php
- src/Environment.php
- src/EnvironmentInterface.php
- src/Event/AbstractEvent.php
- tests/unit/EnvironmentTest.php
- tests/unit/Event/AbstractEventTest.php
- tests/unit/Event/FakeEvent.php
Instead of saving this for 2.0, I think it would be very helpful if 1.0 had a generic way to add future "hooks" into the library without needing to break backward compatibility - a basic event dispatcher implementation like this should do the trick.
I considering using PSR-14, but that would require bumping the minimum PHP version to 7.2, which I'm not interested in doing at this time - many people are using this on PHP 7.1 and I want to ensure they have a stable release too.  I also considered pulling in symfony/event-dispatcher but we only need a basic implementation for now.  We can re-evaluate these choices in 2.0.
> Implement event dispatching

- docs/0.18/security.md
- docs/0.19/security.md
- docs/1.0/security.md
max_nesting_level is either INF (default, float), or an integer, it
doesn't make sense to use a string in the documentation.
------------------
Hello,
Spotted this tiny error in the documentation ;)
Cheers,
~Nico
> Fix max_nesting_level example value type on docs/security page

- src/Block/Element/FencedCode.php
- src/Block/Renderer/FencedCodeRenderer.php
- src/Block/Renderer/HtmlBlockRenderer.php
- src/CommonMarkConverter.php
- src/Cursor.php
- src/Delimiter/Processor/DelimiterProcessorCollection.php
- src/Delimiter/Processor/StaggeredDelimiterProcessor.php
- src/DocParser.php
- src/Environment.php
- src/HtmlRenderer.php
- src/Inline/Parser/BacktickParser.php
- src/Inline/Parser/CloseBracketParser.php
- src/Inline/Renderer/HtmlInlineRenderer.php
- src/Util/Configuration.php
- src/Util/RegexHelper.php
- tests/benchmark/benchmark.php
Alternative PR to #388 with many of the same optimizations.  A huge thanks to @ricardofiorani for implementing most of these! :tada: 
**Before:**
```
Running Benchmarks (Isolated), 7 Implementations, 20 Iterations:
CommonMark                     ....................
PHP Markdown                   ....................
PHP Markdown Extra             ....................
Parsedown                      ....................
cebe/markdown                  ....................
cebe/markdown gfm              ....................
cebe/markdown extra            ....................
Benchmark Results, CPU:
1) Parsedown                    1.67 ms              
2) cebe/markdown                1.74 ms      -0.07 ms
3) cebe/markdown extra          2.01 ms      -0.34 ms
4) cebe/markdown gfm …
```
> Performance optimizations

- src/Util/UrlEncoder.php
- tests/unit/Util/UrlEncoderTest.php
Fixes #395
Our previous approach was very naive and did not properly handle non-UTF-8 sequences. With this new approach, invalid UTF-8 sequences are left encoded and valid ones are normalized one character (not byte) at a time.
> Fix URL normalization

- CHANGELOG.md
- src/Converter.php
- src/DocParser.php
- src/DocParserInterface.php
- src/Exception/UnexpectedEncodingException.php
- tests/unit/CommonMarkConverterTest.php
- tests/unit/DocParserTest.php
> Validate encoding

- .phpstorm.meta.php
- docs/1.0/configuration.md
- src/Block/Parser/ListParser.php
- tests/unit/Block/Parser/ListParserTest.php
> Allow the unordered list markers to be configurable

- .phpstorm.meta.php
- docs/1.4/extensions/heading-permalinks.md
- docs/1.4/extensions/overview.md
- docs/_data/menu.yml
- src/Extension/HeadingPermalink/HeadingPermalink.php
- src/Extension/HeadingPermalink/HeadingPermalinkExtension.php
- src/Extension/HeadingPermalink/HeadingPermalinkProcessor.php
- src/Extension/HeadingPermalink/HeadingPermalinkRenderer.php
- src/Extension/HeadingPermalink/Slug/DefaultSlugGenerator.php
- src/Extension/HeadingPermalink/Slug/SlugGeneratorInterface.php
- tests/functional/Extension/HeadingPermalink/HeadingPermalinkExtensionTest.php
- tests/unit/Extension/HeadingPermalink/Slug/DefaultSlugGeneratorTest.php
New extension which automatically adds anchor links to headings, similar to Github:
**Documentation:** https://github.com/thephpleague/commonmark/blob/heading-link-extension/docs/1.3/extensions/heading-permalinks.md
> Implement new heading permalink extension

- docs/1.4/customization/event-dispatcher.md
- src/DocParser.php
- src/Event/DocumentPreParsedEvent.php
- tests/unit/Event/DocumentPreParsedEventTest.php
I have a site with a huge amount of markdown content that uses inline references extensively. Prior to 0.19 I was able to implement reference map caching by overriding DocParser, but now it's final, so it's no longer possible.
It seems that the ability to pre-fill the reference map was envisioned from the very beginning (https://github.com/thephpleague/commonmark/issues/359), so this pull request is a basic attempt to make it happen with events.
> Pre-parsing events

- CHANGELOG.md
- docs/1.4/upgrading.md
- phpstan.neon.dist
- src/CommonMarkConverter.php
- src/Converter.php
- src/ConverterInterface.php
- src/MarkdownConverterInterface.php
- tests/unit/ConverterInterfaceAliasTest.php
Per #438, the `Converter` class doesn't provide any value - it's an unnecessary level of abstraction that nobody really uses.
Deprecating `ConverterInterface` in favor of `MarkdownConverterInterface` is also being done here to make its purpose more clear.  And if we decide to implement HTML-to-Markdown conversion in this library in the future, we can do so by simply implementing a new `HtmlConverterInterface` on the `CommonMarkConverter` in a minor version release (vs adding a new method on the existing interface which would require a major version bump).
Resolves #438
> Add MarkdownConverterInterface; deprecate Converter and ConverterInterface

- src/Extension/HeadingPermalink/HeadingPermalinkProcessor.php
- tests/functional/Extension/HeadingPermalink/HeadingPermalinkExtensionTest.php
The aim of this pull request is to allow text from code-blocks present in Headings to have its text appended during Slug generation, so the contents persist in other attributes, such as the permalink, id and name.
This feature is present currently in GFM, but its not part of the spec. However, it makes sense to keep the inline text, since they're able to be rendered properly, so, why keep the text on the generated slug?
When processing the following piece of Markdown:
```md
```
The output will be:
```html
<h1>
Using <code>my code</code>
<a id="user-content-using" href="#using" name="using" class="permalink" aria-hidden="true" title="Permalink"></a>
</h1>
<h1>
Using my <code>code</code>
<a id="user-content-using-my-code" href="#using-my-code" name="using-my-code" class="permalink" …
```
> Allow for inline code-blocks to render in Heading Permalink's Attributes

- docs/1.4/security.md
Add note that `inner_contents` might be filtered out by HTML post-processing or input filtering.
My use case was that post-processor removed the default `<svg>` node by htmlpurifier (with html5purifier):
- https://github.com/eventum/eventum/blob/v3.8.9/src/Markdown.php#L59
> Document potential issues with additional HTML post-processing

- .travis.yml
Now we are testing the minimum version supported by the package, as well as with the lowest dependencies.
> Test on PHP 7.2.5 lowest

- src/Extension/HeadingPermalink/Slug/DefaultSlugGenerator.php
- tests/unit/Extension/HeadingPermalink/Slug/DefaultSlugGeneratorTest.php
The `DefaultSlugGenerator` implementation currently strips out certain unicode code-points that can render titles in many languages not work properly. 
Test: https://gist.github.com/Ayesh/f357dcc18b60e117ab771476606dda3a
|Heading text|GitHub slug|`league/commonmark` slug|
|---|---|---|
|`Test`|`#test`|`#test`|
|`අත්හදා බලන මාතෘකාව`|`#අත්හදා-බලන-මාතෘකාව`|`#--`|
|`අත්හදා බලන මාතෘකාව -`|`#අත්හදා-බලන-මාතෘකාව---`|`#----`|
|`测试标题`|`#测试标题`|`#`|
|`試験タイトル`|`#試験タイトル`|`#`|
The last second and third strings are from my native Sinhalese language. Some of the glyphs are letters (`\p{L)`), but we also have marks (`\p{M}`). These marks are **not** symbols (`\p{S}`) or punctuation (`\p{P}`). I think the current slug-ify process makes it not possible to use the HeadingPermalink extension in a meaningful …
> Improve DefaultSlugGenerator to preserve complex unicode letters, numbers, and marks

- README.md
With Drupal 9 coming soon, specifying versions here can quickly become outdated. Best to just leave supported versions to the project page itself.
> Remove specific Drupal versions from README.md

- CHANGELOG.md
- docs/1.5/extensions/attributes.md
- docs/1.5/extensions/overview.md
- docs/_data/menu.yml
- src/Extension/Attributes/AttributesExtension.php
- src/Extension/Attributes/Event/AttributesListener.php
- src/Extension/Attributes/Node/Attributes.php
- src/Extension/Attributes/Node/AttributesInline.php
- src/Extension/Attributes/Parser/AttributesBlockParser.php
- src/Extension/Attributes/Parser/AttributesInlineParser.php
- src/Extension/Attributes/Parser/AttributesParserTrait.php
- tests/functional/Extension/Attributes/LocalDataTest.php
- tests/functional/Extension/Attributes/data/code.html
- tests/functional/Extension/Attributes/data/code.md
- tests/functional/Extension/Attributes/data/image.html
- tests/functional/Extension/Attributes/data/image.md
- tests/functional/Extension/Attributes/data/list_attributes.html
- tests/functional/Extension/Attributes/data/list_attributes.md
- tests/functional/Extension/Attributes/data/more_attributes.html
- tests/functional/Extension/Attributes/data/more_attributes.md
- tests/functional/Extension/Attributes/data/special_attributes.html
- tests/functional/Extension/Attributes/data/special_attributes.md
- tests/functional/Extension/Attributes/data/table_attributes.html
- tests/functional/Extension/Attributes/data/table_attributes.md
This extension is based https://github.com/webuni/commonmark-attributes-extension, imported and relicensed with permission from the maintainer: https://github.com/thephpleague/commonmark/issues/474#issuecomment-629954998
Closes #474
> Import the Attributes extension (#484)

- src/CommonMarkConverter.php
Composer finally added a way to query installed versions during runtime:
https://blog.packagist.com/composer-2-development-update/#changelog-
https://github.com/composer/composer/blob/d89342dc434d52c88e0e06ce3982da739a467f13/src/Composer/InstalledVersions.php#L93-L108
> Deprecate CommonMarkConverter::VERSION

- src/Environment.php
Should fix the tests on PHP 8.0 again. :)
> [1.5] Check class_exists before get_parent_class

- .github/workflows/tests.yml
These changes allow the tools to annotate the code with their errors. Note that phpstan already does this as of the most recent patch release 6 days ago, or whenever it was. The other tools need a little bit of help to detect GitHub actions.
The quiet and no-progress flags are not strictly necessary, but they prevent garbled output where progress bars are not rendered correctly (just like you already had).
> [2.0] Nice actions output

- docs/_layouts/homepage.html
On the website the displayed: 
`RIPS SaaSa>` 
Which wasn't intended as far as I know.
So I removed it.
> Removed a typo from the sponsors block.

- README.md
Heyho folks!
Thanks for your awesome work on this library :) 
I created a small extension for my own blogging platform which adds options to lazy load images natively or to integrate with various js libs.
Hope everything is fine and dandy with this PR, feel free to give me any hints if something is missing here or in my extension.
Have cool day and best wishes 👍
Simon vom Eyser
> Add link to lazy image extension

- src/Extension/Footnote/Event/AnonymousFootnotesListener.php
- src/Extension/Footnote/Event/GatherFootnotesListener.php
- src/Extension/Footnote/Parser/AnonymousFootnoteRefParser.php
- src/Extension/Footnote/Parser/FootnoteRefParser.php
- tests/unit/Extension/Footnote/IntegrationTest.php
This PR fixes #524 by removing hard-coded `fn:` and `fnref:` and ensuring that the `footnote/footnote_id_prefix` and `footnote/footnote_ref_prefix` configuration options are always used.
It updates the `AnonymousFootnotesListener`, `GatherFootnotesListener`, `AnonymousFootnoteRefParser`, and `FootnoteRefParser` classes to all be configuration-aware.
I added an integration test in the style of [`Strikethrough/IntegrationTest`](https://github.com/thephpleague/commonmark/blob/latest/tests/unit/Extension/Strikethrough/IntegrationTest.php) to make sure this works, I tried to add unit tests but I couldn't figure out how to render both a footnote _and_ its reference. I'm happy to add more tests if someone can point me in the right direction.
> Fix hard-coded footnote ID config

- src/Extension/Table/TableParser.php
Fixes a couple static calls in `TableParser` class that used static method call pattern (`::`) on non-static calls ('->`).
Thank you.
> Fix non-static methods called as static '::' methods

- src/Extension/CommonMark/Renderer/Block/FencedCodeRenderer.php
Replace a `strlen()` call in `\League\CommonMark\Extension\CommonMark\Renderer\Block\FencedCodeRenderer::render()` with an empty string check.
`strlen()` returns `0` only on an empty string (`""`), so I think it makes sense to simply compare to an empty string, and avoid the `strlen` call.
> Replace a strlen() call in FencedCodeRenderer with an empty string check

- tests/functional/Extension/FrontMatterExtension/FrontMatterExtensionTest.php
- tests/unit/Renderer/HtmlRendererTest.php
- Remove unnecessary `(string)` type cast on \League\CommonMark\Output\RenderedContent::getContent whose interface is declared with a `string` return type and is guaranteed to be a string.
- Remove a few similar `(string)` type casts in \League\CommonMark\Tests\Unit\Renderer\HtmlRendererTest class.
Thank you.
> Remove unnecessary `(string)` type cast

- src/Extension/Footnote/Event/GatherFootnotesListener.php
- src/Extension/Mention/Generator/CallbackGenerator.php
- src/Extension/TaskList/TaskListItemMarker.php
- src/Input/MarkdownInput.php
- src/Parser/Block/BlockStart.php
- tests/benchmark/benchmark.php
- tests/functional/AbstractSpecTest.php
- Removes unnecessary class property default values that are immediately overriden in the constructor. Some of them were left to improve clarity.
- Replaced cascading `str_replace()` calls that do not contain recurring replacements with a single `strtr` call.
- Replaced an unnecessary `preg_split()` with `explode()`.
- Removed an `intval()` call with an `(int)` cast.
- Replaced a `call_user_func_array()` call with more appropriate `call_user_func` call.
> Misc performance and code clarity improvements

- CHANGELOG.md
- composer.json
- src/Extension/Autolink/UrlAutolinkProcessor.php
- src/Util/RegexHelper.php
- tests/unit/Extension/Autolink/UrlAutolinkProcessorTest.php
So, a funny thing has happened where both commonmark.js and GFM forgot to tag releases, despite commonmark.js saying there was a release (0.19.2) and GFM claiming there is a release (0.29.0.gfm.1) too and quoting it in a security vulnerability report from 7 days ago! With all this in mind, I think we should treat their current states as the intended releases, so I have... GFM seem to have changed their autolinking rules to say that all trailing parens should be treated as not part of the link. I have updated the autolink extension as appropriate (indeed, the old implementation failed their tests before):
```
Unexpected result:
=== markdown ===============
www.google.com/search?q=Markup+(business)
www.google.com/search?q=Markup+(business)))
(www.google.com/search?q=Markup+(business)) …
```
> [1.5] Fixed GFM autolinking spec compliance

- src/Environment/Environment.php
Fixes a missing scalar type in the first parameter of `\League\CommonMark\Environment\Environment::getConfig()`. This method does not follow [LSP](https://php.watch/articles/php-lsp) and errors out.
> Fix LSP incompatibility in \League\CommonMark\Environment\Environment::getConfig

- CHANGELOG.md
- composer.json
- docs/2.0/customization/event-dispatcher.md
- src/Environment/Environment.php
- src/Environment/EnvironmentInterface.php
- src/Event/AbstractEvent.php
- src/Event/ListenerData.php
- tests/unit/Environment/EnvironmentTest.php
- tests/unit/Event/FakeEventParent.php
This PR makes the event system fully compatible with PSR-14! :tada: 
Users can even swap in their own PSR-14 event dispatcher, though this does require that external dispatcher to support registering events via `ListenerProviderInterface` instances, which not all do.
Resolves #436
> Make PSR-14 compliant

- docs/1.5/extensions/mentions.md
- docs/2.0/extensions/mentions.md
When reviewing the docs, I was slowed by trying to grok the ascii based illustration of String-Based URL Templates for the Mention extension. It took a moment to understand that the `Identifier` underline wasn't offset, but pointing to two different areas (`colinodell`) and not highlighting the section above it `dell" => https://www.twitter.com/colin`.
I've switched it to use some of the additional ascii characters to highlight that the `colinodell` to the direct right of the `@` symbol was the identifier that was carried over to the value on the right. I also used an arrow instead of carot and put `Symbol` on the same line as `Identifier`, giving them equal weight.
RE: #553
> Use alternative ascii characters in string template illustration

- docs/1.5/basic-usage.md
- docs/1.5/command-line.md
- docs/1.5/configuration.md
- docs/1.5/customization/abstract-syntax-tree.md
- docs/1.5/customization/block-parsing.md
- docs/1.5/customization/block-rendering.md
- docs/1.5/customization/delimiter-processing.md
- docs/1.5/customization/environment.md
- docs/1.5/customization/event-dispatcher.md
- docs/1.5/customization/extensions.md
- docs/1.5/customization/inline-parsing.md
- docs/1.5/customization/inline-rendering.md
- docs/1.5/customization/overview.md
- docs/1.5/extensions/attributes.md
- docs/1.5/extensions/autolinks.md
- docs/1.5/extensions/commonmark.md
- docs/1.5/extensions/disallowed-raw-html.md
- docs/1.5/extensions/external-links.md
- docs/1.5/extensions/footnotes.md
- docs/1.5/extensions/heading-permalinks.md
- docs/1.5/extensions/inlines-only.md
- docs/1.5/extensions/mentions.md
- docs/1.5/extensions/smart-punctuation.md
- docs/1.5/extensions/strikethrough.md
- docs/1.5/extensions/table-of-contents.md
- docs/1.5/extensions/tables.md
- docs/1.5/extensions/task-lists.md
- docs/1.5/index.md
- docs/1.5/installation.md
- docs/1.5/security.md
Made a pass on consistent use of code block formatting through the `1.5` docs. I made a few assumptions in applying the changes:
- Backticks are preferred over indentation and tildes
- 42 `php` code blocks used backticks (`rg -U '```php\s+' | wc -l`) vs 35 `php` code blocks using tildes (`rg -U '~~~php\s+' | wc -l`)
- `php` code blocks should not include PHP open tags (`<?php`)
- 88 `php` code blocks did not include an open tag (`rg -U '(```|~~~)php\s+[^<]' | wc -l`) vs 66 `php` code blocks included an open tag (`rg -U '(```|~~~)php\s+[<]' | wc -l`)
- Code blocks should specify their language
- `markdown` is preferred over `md` for it's explicitness
I was unable to covers two points made in #553:
> - Editing documentation for older versions without also applying the same changes to newer …
```
> Code block consistency

- docs/0.19/installation.md
- docs/1.0/installation.md
- docs/1.3/installation.md
- docs/1.4/installation.md
- docs/1.5/installation.md
- docs/2.0/installation.md
The installation instructions mention enabling "autoloading" for
composer-installed packages.
The composer project has moved this documentation from the intro-page,
to the "basic usage"-page, which broke the link in our docs.
This commit fixes it for all versions of the documentation.
> Update the link for autoloading with composer

- docs/0.19/basic-usage.md
- docs/0.19/installation.md
- docs/1.0/basic-usage.md
- docs/1.0/installation.md
- docs/1.3/basic-usage.md
- docs/1.3/installation.md
- docs/1.4/basic-usage.md
- docs/1.4/installation.md
- docs/1.5/basic-usage.md
- docs/1.5/installation.md
- docs/2.0/basic-usage.md
- docs/2.0/installation.md
If someone is new with composer (which is entirely possible) it might be confusing to get a "class not found" error when copy/pasting the example code.
This commit adds including the autoloader to the examples for basic usage, so they can be literally copy/pasted in a text editor and will work right away.
This can make it easier to get started for beginners.
> Autoloader instructions

- docs/1.3/basic-usage.md
- docs/1.4/basic-usage.md
- docs/1.5/basic-usage.md
- docs/2.0/basic-usage.md
On the "Basic Usage"-pages (e.g. https://commonmark.thephpleague.com/1.5/basic-usage/) the "extensions"-link currently goes to /extensions/ which results in a 404 on the live website.
e.g. https://commonmark.thephpleague.com/1.5/extensions/
This commit changes it to /extensions/overview/ for the relevant versions.
e.g. https://commonmark.thephpleague.com/1.5/extensions/overview/
> Fix broken link to extensions from "Basic Usage"

- docs/0.19/installation.md
- docs/1.0/installation.md
- docs/1.3/installation.md
- docs/1.4/installation.md
- docs/1.5/installation.md
- docs/2.0/installation.md
The website for Composer has changed the hash for Caret Version Range
in the docs, so the links in the docs are now incorrect.
This commit simply replaces the "broken" link with the correct one.
Note that the link did not 404, it's just the hash.
> Update links to the Caret Version Range docs

- CHANGELOG.md
- src/Extension/Mention/Mention.php
- src/Extension/Mention/MentionExtension.php
- src/Extension/Mention/MentionParser.php
- tests/functional/Extension/Mention/MentionExtensionTest.php
- tests/functional/Extension/Mention/MentionParserTest.php
- tests/unit/Extension/Mention/Generator/CallbackGeneratorTest.php
- tests/unit/Extension/Mention/MentionTest.php
Once #550 is merged we should also consider renaming "symbol" (which implies a single character) to "prefix" for v2.0 onwards.
Because this would be a breaking change to configuration inputs (against the spirit of #475) we could release a new patch version for 1.x where both `symbol` and `prefix` are allowed as configuration keys but a deprecation notice is raised if `symbol` is used.
WDYT @markcarver?
(Note that this PR is based directly on the commit history present in #550)
> Rename "symbol" option to "prefix"

- CHANGELOG.md
- src/Extension/Mention/MentionParser.php
- tests/functional/Extension/Mention/MentionParserTest.php
Thanks to #549 we're able to implement this for the upcoming 2.0 release
Resolves #514
> Allow more than one character to be used as a symbol for MentionExtension

- docs/custom.css
This PR adds inheritance to all possible direct children of a table header in the docs.
Currently, the `th` styles are bypassed by the styles of the child element. 
E.g. https://commonmark.thephpleague.com/1.5/upgrading/
> Fix styles in table headings

- docs/custom.css
Hey there! I added a few style tweaks to the CSS to accommodate for smaller mobile screens, including preventing the header logo from being cutoff, and adding Flexbox in a couple places to help keep the layout responsive.
> Add minor style tweaks for smaller mobile screens

- src/Extension/Mention/Mention.php
- src/Extension/Mention/MentionExtension.php
- src/Extension/Mention/MentionParser.php
- tests/functional/Extension/Mention/MentionParserTest.php
- tests/unit/Extension/Mention/Generator/CallbackGeneratorTest.php
- tests/unit/Extension/Mention/Generator/StringTemplateLinkGeneratorTest.php
- tests/unit/Extension/Mention/MentionTest.php
While working on https://www.drupal.org/project/markdown/issues/3160927, I suddenly realized that there's no "easy" way to determine which mention is being used by the generator callback we're using, thus I cannot load that specific mention's configuration (has much more than the normal mention due to CMS integrations).
Since the changes to these classes are mostly internal, I figured it wouldn't hurt to add a new parameter that names the mention (which is automatically pulled from the mention configuration as the array key).
> Add “name” property to mentions so implementers can identify which mention is which

- docs/2.0/installation.md
When version 2.0 goes stable, it will be as easy as is currently
documented:
```bash
composer require "league/commonmark:^2.0"
```
Right now however, there's a good chance people have their composer
settings set to have a minimum stability of "stable".[1]
This will probably result in errors when trying to run this command.
I wasn't sure what the best way forward is for here: leave in the old,
but make a note of it? Make temporary instructions for dev?
For now I went with a combination: leave the current way (with just
`composer require`), but add some instructions for the current dev
version.
When this version goes stable the extra instructions can easily be
deleted from the document.
[1] This is the issue I ran into myself when I tried to play around with 
the 2.0 version. This PR is my …
> Add instructions on how to install dev version

- docs/custom.css
This PR adds a `max-width` on paragraphs, to limit the line length and improve the readabillity on larger screens.
> Docs: Improve readabillity on large screens

- CHANGELOG.md
- src/Extension/Mention/MentionParser.php
- tests/functional/Extension/Mention/MentionParserTest.php
(Copied from https://github.com/thephpleague/commonmark/pull/581)
**Version(s) affected**: 1.5.6
**Description**  
If a mention immediately follows a new line or any other non-word character it doesn't get converted to a link.
**How to reproduce**  
```php
$environment = Environment::createGFMEnvironment();
$environment->addExtension(new MentionExtension());
$converter = new GithubFlavoredMarkdownConverter(
[
'mentions' => [
'github_handle'  => [
'symbol'    => '@',
'regex'     => '/^[a-z\d](?:[a-z\d]|-(?=[a-z\d])){0,38}(?!\w)/',
'generator' => 'https://github.com/%s',
]
],
],
$environment
);
echo $converter->convertToHtml("@test\n@test");
```
Results in:
```html
<p><a href="https://github.com/test">@test</a>
@test</p>
```
instead of
```html
<p><a href="https://github.com/test">@test</a> …
```
> Fix mentions when they appear after a non-word character such as \n or ,

- README.md
Hey @colinodell,
I've build a static-generator to use within Laravel. It takes commonmark files with frontmatter and generates pages to publish in the `public` directory. Do you think it could be added to the "Integrations" section?
Happy New Year,
Peter
> Adding spekulatius/laravel-commonmark-blog

- docs/1.3/extensions/disallowed-raw-html.md
- docs/1.4/extensions/disallowed-raw-html.md
- docs/1.5/extensions/disallowed-raw-html.md
- docs/1.6/extensions/disallowed-raw-html.md
- docs/2.0/extensions/disallowed-raw-html.md
Replace DisallowedRawHTMLExtension with DisallowedRawHtmlExtension (Html instead of HTML) in documentation
fixes #599
> Resolve casing error in documentation of DisallowedRawHtmlExtension

- .github/workflows/tests.yml
Code coverage is failing in CI but the job still passes due to `continue-on-error: true`
```
In RepositoryIntrospector.php line 39:
Failed to retrieve commit parents. If you use a shallow git checkout, pleas  
e checkout at least a depth of one.                                          
code-coverage:upload [--api-url API-URL] [--repository REPOSITORY] [--revision REVISION] [--format FORMAT] [--parent PARENT] [--] <coverage-file>
```
> ci: fix code coverage

- CHANGELOG.md
- composer.json
- src/Extension/CommonMark/Parser/Block/HtmlBlockStartParser.php
- src/Extension/CommonMark/Parser/Inline/HtmlInlineParser.php
- src/Normalizer/TextNormalizer.php
- src/Parser/Inline/InlineParserMatch.php
- src/Util/LinkParserHelper.php
- src/Util/RegexHelper.php
- tests/functional/RegressionTest.php
- tests/unit/Parser/Inline/InlineParserMatchTest.php
- tests/unit/Util/RegexHelperTest.php
This brings the `2.0` branch into compliance with the latest changes and regression tests included in the 0.30.0 spec.
Closes #679
> CommonMark spec 0.30.0

- docs/2.0/extensions/mentions.md
this PR adds import class for `MentionGeneratorInterface`, `Mention` and `AbstractInline` which can be imported from `commonmark` package.
> Add missing import for available classes

- CHANGELOG.md
- docs/2.0/customization/block-parsing.md
- src/Environment/Environment.php
- src/Parser/Block/BlockStart.php
- src/Parser/Block/SkipLinesStartingWithLettersParser.php
- src/Parser/MarkdownParser.php
- tests/unit/Environment/EnvironmentTest.php
Fixes #706 by moving the optimization into a "parser" so that users have the opportunity to register their parsers with a higher priority than the optimization where needed.
> Fix ability to register block parsers that identify lines starting with letters

- docs/2.0/xml.md
On the ["XML Rendering"](https://commonmark.thephpleague.com/2.0/xml/) page, the "custom extensions" link currently goes to `/customization/` which results in [a 404 on the live website](https://commonmark.thephpleague.com/2.0/customization/).
This commit changes it to `/customization/overview/` for the relevant version.
> Fixed link to custom extensions overview

- docs/2.0/extensions/heading-permalinks.md
- src/Extension/HeadingPermalink/HeadingPermalinkExtension.php
- src/Extension/HeadingPermalink/HeadingPermalinkRenderer.php
- tests/functional/Extension/HeadingPermalink/HeadingPermalinkExtensionTest.php
First time contributor.
Was running performance tests through various providers. [web.dev](https://web.dev/measure/) flagged one of the pages for accessibility due to `aria-hidden` being placed on a focusable element (see [discussion](https://github.com/thephpleague/commonmark/discussions/738)).
Personal goal of creating a good, accessible experience - not to be "technically accessible" (used by visually impaired accessibility expert I worked with once describing a website).
This seemed the lowest impact (a minor or patch release eligible) change.
1. [x] Created config option `aria_hidden` with a default of `true` to maintain backward compatibility.
2. [x] Verified current test suite passes using default config.
3. [x] Updated `testHeadingPermalinksWithCustomOptions` to use optional …
> Permalinks aria hidden

- src/Util/ArrayCollection.php
Prevent deprecated warning on ArrayAccess with PHP 8.1
> PHP 8.1 deprecated warning

- src/Environment/Environment.php
- tests/unit/Environment/EnvironmentTest.php
Minor thing to remove deprecation warnings when using Symfony 5.4/6.0.
Refs:
1. https://symfony.com/blog/preparing-your-apps-and-bundles-for-symfony-6
2. https://wouterj.nl/2021/09/symfony-6-native-typing
3. https://github.com/twigphp/Twig/runs/4684887490?check_suite_focus=true#step:12:17
> Add object return type to Environment::dispatch()

- CHANGELOG.md
- src/Renderer/DocumentRendererInterface.php
- src/Renderer/HtmlRenderer.php
- src/Xml/MarkdownToXmlConverter.php
- src/Xml/XmlRenderer.php
`MarkdownRendererInterface` is poorly named, so deprecate it in favor of a new `DocumentRendererInterface`
This new interface will be needed for #419 and #719
> DocumentRendererInterface

- docs/2.0/customization/block-parsing.md
- docs/2.1/customization/block-parsing.md
- docs/2.2/customization/block-parsing.md
Moved the description of `tryContinue()` from under the heading for `closeBlock()`.
> Fix position of description of tryContinue

- .github/workflows/backwards-compatibility.yml
- .github/workflows/tests.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- src/Extension/Attributes/Util/AttributesHelper.php
Inform phpstan of the desired array types so it stops erroring on newer versions.
> Fix phpstan error

- README.md
It allows users to use == in order to indicate text that should be rendered within `mark` tags.
> Added MarkerExtension to Community Extensions List

- CHANGELOG.md
- src/Extension/Attributes/Util/AttributesHelper.php
- src/Util/RegexHelper.php
- tests/functional/AbstractLocalDataTest.php
- tests/functional/Extension/Attributes/data/special_attributes.html
- tests/functional/Extension/Attributes/data/special_attributes.md
- tests/unit/Extension/Attributes/Util/AttributesHelperTest.php
As discovered in #943 and #944, unquoted attribute parsing sometimes consumes the trailing curly brace as part of the attribute value, causing the lazy check for the brace to fail.  This PR adjusts the parsing logic to match and extract the inner attributes from the `{ ... }` syntax first to avoid this.
> Fix attribute parsing

- docs/2.0/customization/extensions.md
- docs/2.1/customization/extensions.md
- docs/2.2/customization/extensions.md
- docs/2.3/customization/extensions.md
`ConfigurableEnvironmentInterface` appears to be a vestige of the 1.x branch.
https://github.com/thephpleague/commonmark/blob/1.6/src/ConfigurableEnvironmentInterface.php
`EnvironmentBuilderInterface` appears to be the corresponding interface used by `ExtensionInterface` in 2.x branches.
https://github.com/thephpleague/commonmark/blob/2.3/src/Extension/ExtensionInterface.php#L19-L23
This issue appears to be present in the docs for all 2.x branches.
- https://github.com/thephpleague/commonmark/blob/2.3/docs/2.3/customization/extensions.md?plain=1#L16-L20
- https://github.com/thephpleague/commonmark/blob/2.2/docs/2.2/customization/extensions.md?plain=1#L15-L19
- https://github.com/thephpleague/commonmark/blob/2.1/docs/2.1/customization/extensions.md?plain=1#L16-L20
- …
> Fix class reference in Extensions section of docs

- .github/workflows/backwards-compatibility.yml
- CHANGELOG.md
- composer.json
- phpstan.neon.dist
- src/Extension/Autolink/UrlAutolinkParser.php
- src/Extension/Footnote/Renderer/FootnoteBackrefRenderer.php
- src/Extension/Footnote/Renderer/FootnoteRefRenderer.php
- src/Extension/Footnote/Renderer/FootnoteRenderer.php
- src/Normalizer/SlugNormalizer.php
- src/Parser/InlineParserContext.php
- src/Parser/InlineParserEngine.php
- src/Reference/ReferenceParser.php
- src/Util/LinkParserHelper.php
- src/Util/RegexHelper.php
- tests/phpstan/MbstringFunctionCallRule.php
- tests/unit/Parser/InlineParserEngineTest.php
Fixes parsing issues when `mb_internal_encoding()` is set to something other than `UTF-8`
Fixes #951
> Fix mbstring calls without explicit encoding

- CHANGELOG.md
- src/Extension/Autolink/UrlAutolinkParser.php
- tests/functional/Extension/Autolink/UrlAutolinkParserTest.php
The extension was not detecting URI with a `_` symbol correctly.
The issue was already fixed in [the regex used by the Symfony project](https://github.com/symfony/symfony/blob/7b0ca3ab5678232f876a95991b66778f4aaa33e3/src/Symfony/Component/Validator/Constraints/UrlValidator.php#L25-L41).
The regex used by the extension is updated to integrate all the changes that been made to it.
> Fix autolink extension URL detection

- CHANGELOG.md
- docs/2.4/extensions/tables.md
- src/Extension/Table/TableCellRenderer.php
- src/Extension/Table/TableExtension.php
- tests/unit/Extension/Table/TableCellRendererTest.php
This PR introduces a new config option to control whether table cell alignment is rendered using `style` or `align` attributes. See #958 for more context.
> Table alignment config option

- CHANGELOG.md
- src/Extension/Strikethrough/StrikethroughDelimiterProcessor.php
- tests/functional/Extension/Strikethrough/StrikethroughExtensionTest.php
See https://github.com/github/cmark-gfm/issues/271. **TL;DR:** Strikethrough requires a matching pair of 1 or 2 tildes, instead of 2+.
Unfortunately, due to https://github.com/github/cmark-gfm/issues/288, the `spec.txt` we test against does not yet have these changes, so we'll rely on our own tests to verify this modified behavior for now.
> Update Strikethrough parsing to match GFM spec

- docs/2.0/extensions/autolinks.md
- docs/2.1/extensions/autolinks.md
- docs/2.4/extensions/autolinks.md
Currently those links 404 because they link to `mention` instead of `mentions`.
> Fix links to `Mentions` extension documentation

- docs/2.0/index.md
- docs/2.1/index.md
- docs/2.2/index.md
- docs/2.3/index.md
- docs/2.4/index.md
The example on the home page for 2.x didn't include:
1. a call to `getContent()` and
2. a comma in "Hello, World!"
> fix: Home page examples since 2.0

- CHANGELOG.md
- src/Extension/Attributes/Util/AttributesHelper.php
- src/Util/RegexHelper.php
- tests/functional/Extension/Attributes/data/special_attributes.html
- tests/functional/Extension/Attributes/data/special_attributes.md
- tests/unit/Extension/Attributes/Util/AttributesHelperTest.php
As said in #985, this is my attempt at allowing valueless attributes to be set on elements.
> Allow adding attributes without value

- CHANGELOG.md
- docs/2.5/extensions/autolinks.md
- src/Extension/Autolink/AutolinkExtension.php
- src/Extension/Autolink/UrlAutolinkParser.php
- tests/functional/Extension/Autolink/UrlAutolinkParserTest.php
This is an alternative approach to #969 allowing users to customize both the default and allowed protocols via configuration.
> Make autolinking protocols configurable

- CHANGELOG.md
- src/Extension/ExternalLink/ExternalLinkProcessor.php
- tests/functional/Extension/ExternalLink/ExternalLinkExtensionTest.php
> Fix ExternalLinkProcessor not fully disabling the `rel` attribute

- docs/2.4/extensions/footnotes.md
It should be `backref_symbol`, not `symbol`.
> Replace symbol with backref_symbol

- src/Extension/SmartPunct/QuoteParser.php
- According to the [reference](https://wiki.php.net/rfc/spread_operator_for_array), it's great to use the spread array operator to replace the `array_merge` function.
- There're two reasons about using the spread array operator:
- Spread operator should have a better performance than array_merge and compile time optimization can be performant for constant arrays.
- `array_merge` only supports array, while the spread operator also supports objects implementing `Traversable`.
> Replace the array_merge with spread array operator

- src/Extension/Attributes/Util/AttributesHelper.php
- tests/functional/Extension/Attributes/data/class_names.html
- tests/functional/Extension/Attributes/data/class_names.md
The [CSS level 3 Syntax](https://www.w3.org/TR/selectors-3/), which is a Recommendation since 2018, allows much more characters in `id` and `class` selectors than the ones currently supported by the "Attributes" extension:
https://github.com/thephpleague/commonmark/blob/91c24291965bd6d7c46c46a12ba7492f83b1cadf/src/Extension/Attributes/Util/AttributesHelper.php#L26
The formal CSS level 3 selectors grammar is detailed here: https://www.w3.org/TR/selectors-3/#w3cselgrammar
This pull request adds a test to check several valid `class` and `id` names that are currently failing to be parsed as valid attribute values by the "Attributes" extension, and it proposes a fix for this issue.
> Allow CSS level 3 selectors for classes and ids in the attributes extension

- CHANGELOG.md
- composer.json
- src/Extension/CommonMark/Node/Block/ListBlock.php
- src/Extension/CommonMark/Parser/Block/FencedCodeParser.php
- src/Extension/CommonMark/Parser/Block/IndentedCodeParser.php
- src/Extension/CommonMark/Parser/Block/ListBlockParser.php
- src/Extension/CommonMark/Parser/Block/ListBlockStartParser.php
- src/Extension/CommonMark/Parser/Block/ListItemParser.php
- src/Node/Block/Paragraph.php
- src/Parser/Block/DocumentBlockParser.php
- src/Parser/Block/ParagraphParser.php
- src/Parser/MarkdownParser.php
- src/Util/RegexHelper.php
- tests/functional/CommonMarkJSRegressionTest.php
- tests/unit/Util/RegexHelperTest.php
This PR brings our library into compliance with [the latest version (0.31) of the CommonMark spec](https://spec.commonmark.org).
> CommonMark spec 0.31 compatibility

- src/Extension/Attributes/Util/AttributesHelper.php
- tests/functional/Extension/Attributes/data/special_attributes.html
- tests/functional/Extension/Attributes/data/special_attributes.md
- tests/unit/Extension/Attributes/Util/AttributesHelperTest.php
This PR prevents mustache-style template language strings being interpreted as attributes.
This was introduced in 2.5.0 by #986. It caused template strings to be wiped out.
```php
$converter->convert('# Hello {{ foo }}');
```
```diff
-<h1>Hello {{ foo }}</h1>
+<h1>Hello {}</h1>
```
This PR adds negative lookaheads to the regex to ignore the double-braces, allowing the template strings to be maintained:
```diff
-<h1>Hello {}</h1>
+<h1>Hello {{ foo }}</h1>
```
I'm not sure if the changes to `AttributesHelperTest` are needed. They passed before making the regex change too.
> Prevent templating being treated as attributes

- CHANGELOG.md
- src/Parser/MarkdownParser.php
- tests/functional/Extension/Table/TableMarkdownTest.php
Fixes #1037 where Tables (and other blocks that replace partially-parsed paragraphs) have incorrect start line numbers.
> Fix table start line numbers

- docs/2.5/extensions/attributes.md
- src/Extension/Attributes/Util/AttributesHelper.php
- tests/functional/Extension/Attributes/data/special_attributes.html
- tests/functional/Extension/Attributes/data/special_attributes.md
- tests/unit/Extension/Attributes/Util/AttributesHelperTest.php
As stated in https://github.com/thephpleague/commonmark/pull/1035#issuecomment-2284664894, the PR #986 , which introduced the ability to create valueless attributes using the Attributes extension, causes issues when a markdown document includes text strings that contain curly braces.
For example, the following markdown text
```md
Elastic{ON} Tour San Francisco
```
is rendered by [the official commonmark dingus](https://spec.commonmark.org/dingus/) as:
```html
<p>Elastic{ON} Tour San Francisco</p>
```
The `league/commonmark` library with the "Attributes" extension enabled was used to render such markdown the same way until the commit 2138460860e2cee78498846a9d6e2da1913bbadb. Since then, it renders this markdown as:
```html
<p>Elastic Tour San Francisco</p>
```
which is obviously something …
> Fix the parser behavior for texts containing curly-braces when the Attributes extension is enabled

- docs/2.5/extensions/autolinks.md
The current docs result in an error:
```
[League\Config\Exception\ValidationException] Unexpected item 'autolink › default_protocols', did you mean 'default_protocol'? 
```
> Fixed config typo in autolinks.md

- docs/2.5/extensions/embed.md
I ran into this error with a fresh install - as have several other people. This clarifies that it isn't sufficient just to install the library.
The error was:
> `PHP Fatal error:  Uncaught RuntimeException: No ResponseFactoryInterface detected in /vendor/embed/embed/src/Http/FactoryDiscovery.php:61`
> Documentation update for embed.md

- src/Extension/Strikethrough/StrikethroughDelimiterProcessor.php
This PR removes a call to `min()` for two values that by virtue of the previous if statement must already be exactly identical. As they are always the same we can remove both the call to `min()` and one of the two `->getLength()` calls.
> Remove redundant code

- CHANGELOG.md
- src/Extension/CommonMark/Renderer/Block/ListItemRenderer.php
- tests/functional/CMarkRegressionTest.php
- tests/functional/CommonMarkJSRegressionTest.php
- tests/functional/Extension/Autolink/UrlAutolinkParserTest.php
- tests/functional/Extension/Footnote/spec.txt
- tests/functional/Extension/TableOfContents/md/custom-class.html
- tests/functional/Extension/TableOfContents/md/headings-with-inlines.html
- tests/functional/Extension/TableOfContents/md/html-in-headings.html
- tests/functional/Extension/TableOfContents/md/min-max.html
- tests/functional/Extension/TableOfContents/md/position-before-headings.html
- tests/functional/Extension/TableOfContents/md/position-placeholder-multiple.html
- tests/functional/Extension/TableOfContents/md/position-top.html
- tests/functional/Extension/TableOfContents/md/sample.html
- tests/functional/Extension/TableOfContents/md/setext-headings.html
- tests/functional/Extension/TableOfContents/md/style-bullet.html
- tests/functional/Extension/TableOfContents/md/style-ordered.html
- tests/functional/Extension/TableOfContents/md/weird-as-is.html
- tests/functional/Extension/TableOfContents/md/weird-flattened.html
- tests/functional/Extension/TableOfContents/md/weird-relative.html
- tests/unit/Extension/TaskList/TaskListExtensionTest.php
Fixes #1059 by ensuring that we only add newlines around block-level elements (instead of around any HTML elements)
> Rendered list items should only add newlines around block-level children

- docs/2.6/customization/extensions.md
just updating the docs for prevent confusing for other developers when trying to build custom extensions
> fix incorrect interface in docs v2.6

- docs/2.0/extensions/front-matter.md
- docs/2.1/extensions/front-matter.md
- docs/2.2/extensions/front-matter.md
- docs/2.3/extensions/front-matter.md
- docs/2.4/extensions/front-matter.md
- docs/2.5/extensions/front-matter.md
- docs/2.6/extensions/front-matter.md
There's a missing newline between imports in one of the documentation examples for the Front Matter extension that affects its readability.
> Add missing newline in Front Matter documentation example

- docs/2.6/extensions/front-matter.md
In docs/2.6/extensions/front-matter.md, add a missing newline so that `use` statements are on individual lines
> docs/2.6/extensions/front-matter.md: add missing newline
