CHANGELOG.md
phpunit.xml.dist
src/Block/Renderer/HorizontalRuleRenderer.php
src/Block/Renderer/HtmlBlockRenderer.php
src/Block/Renderer/IndentedCodeRenderer.php
src/Inline/Element/AbstractInlineContainer.php
src/Inline/Element/AbstractWebResource.php
tests/Block/Renderer/BlockQuoteRendererTest.php
tests/Block/Renderer/DocumentRendererTest.php
tests/Block/Renderer/FencedCodeRendererTest.php
tests/Block/Renderer/HeaderRendererTest.php
tests/Block/Renderer/HorizontalRuleRendererTest.php
tests/Block/Renderer/HtmlBlockRendererTest.php
tests/Block/Renderer/IndentedCodeRendererTest.php
tests/Block/Renderer/ListBlockRendererTest.php
tests/Block/Renderer/ListItemRendererTest.php
tests/Block/Renderer/ParagraphRendererTest.php
tests/EnvironmentTest.php
tests/FakeEmptyHtmlRenderer.php
tests/FakeHtmlRenderer.php
tests/Inline/Renderer/CodeRendererTest.php
tests/Inline/Renderer/EmphasisRendererTest.php
tests/Inline/Renderer/ImageRendererTest.php
tests/Inline/Renderer/LinkRendererTest.php
tests/Inline/Renderer/NewlineRendererTest.php
tests/Inline/Renderer/RawHtmlRendererTest.php
tests/Inline/Renderer/StrongRendererTest.php
tests/Inline/Renderer/TextRendererTest.php

Unit tests to increase code coverage and overall quality.
Also contains a couple minor changes noticed while writing/executing the tests.

Code quality

---

src/Block/Element/AbstractBlock.php
src/Block/Renderer/DocumentRenderer.php
src/Inline/Element/AbstractStringContainer.php
src/Inline/Parser/NewlineParser.php
src/Inline/Processor/EmphasisProcessor.php
src/Util/LinkParserHelper.php
tests/Block/Renderer/ListItemRendererTest.php
tests/CursorTest.php

While digging deeper in the code my IDE noticed some minor phpdoc and PSR-2 issues.

Minor phpdoc and PSR-2 fixes

---

.gitignore
CHANGELOG.md
README.md

0.8 release

---

src/Block/Element/AbstractBlock.php
src/Block/Element/ListBlock.php
src/Block/Element/ListItem.php

Similarly as in inline element https://github.com/thephpleague/commonmark/blob/master/src/Inline/Element/AbstractInline.php#L24

Added storage to block element for arbitrary data

---

README.md

Refs https://github.com/thephpleague/oauth2-server/commit/c174b6fc65f034dd6547da6ab7bb429a20988eb0

Add integrations list

---

CHANGELOG.md
src/ReferenceParser.php

Fixes #120.
See also:
- https://github.com/jgm/commonmark.js/issues/39
- https://github.com/jgm/commonmark.js/pull/49
- https://github.com/jgm/commonmark.js/commit/7d6dd86613a602fd0557cfd4b23cc972c7da8a89

Fix link reference definition edge case (#120)

---

CHANGELOG.md
src/Util/LinkParserHelper.php
src/Util/RegexHelper.php

Fixes #118 and #119.  Also increases the max link label size to 999 per the spec.

Link fixes

---

.styleci.yml

Add configuration for StyleCI (#133)

---

src/Inline/Parser/SmartPunctParser.php

This just looked funny before to me.

Minor style tweak

---

src/Inline/Parser/QuoteParser.php

See jgm/commonmark.js@ddd2f5e3adc0e29aa354837a5e4b3014dfff3311

Change double quote algorithm to match spec

---

CHANGELOG.md
src/Block/Element/AbstractBlock.php
src/Block/Renderer/BlockQuoteRenderer.php
src/Block/Renderer/FencedCodeRenderer.php
src/Block/Renderer/HeaderRenderer.php
src/Block/Renderer/HorizontalRuleRenderer.php
src/Block/Renderer/IndentedCodeRenderer.php
src/Block/Renderer/ListBlockRenderer.php
src/Block/Renderer/ListItemRenderer.php
src/Block/Renderer/ParagraphRenderer.php
src/Inline/Element/AbstractInline.php
src/Inline/Renderer/CodeRenderer.php
src/Inline/Renderer/EmphasisRenderer.php
src/Inline/Renderer/ImageRenderer.php
src/Inline/Renderer/LinkRenderer.php
src/Inline/Renderer/StrongRenderer.php
tests/unit/Block/Renderer/BlockQuoteRendererTest.php
tests/unit/Block/Renderer/FencedCodeRendererTest.php
tests/unit/Block/Renderer/HeaderRendererTest.php
tests/unit/Block/Renderer/IndentedCodeRendererTest.php
tests/unit/Block/Renderer/ListBlockRendererTest.php
tests/unit/Block/Renderer/ListItemRendererTest.php
tests/unit/Block/Renderer/ParagraphRendererTest.php
tests/unit/Inline/Renderer/CodeRendererTest.php
tests/unit/Inline/Renderer/EmphasisRendererTest.php
tests/unit/Inline/Renderer/ImageRendererTest.php
tests/unit/Inline/Renderer/LinkRendererTest.php
tests/unit/Inline/Renderer/StrongRendererTest.php

This is identical to #101, but with the merge conflicts resolved.
Full credit goes to @hason for implementing this - thanks a ton!

Added support for tag attributes in renderers

---

src/Block/Element/AbstractBlock.php
src/ElementRendererInterface.php
src/Environment.php
src/HtmlRenderer.php
src/Inline/Element/AbstractInline.php
src/Util/ArrayCollection.php
src/Util/Configuration.php

https://github.com/thephpleague/commonmark/pull/165#discussion_r35483315

Replace mixed|null with mixed in docblocks

---

CHANGELOG.md
composer.json
src/Block/Element/AbstractBlock.php
src/Block/Element/BlockQuote.php
src/Block/Element/FencedCode.php
src/Block/Element/ListItem.php
src/Block/Parser/HorizontalRuleParser.php
src/Cursor.php
src/DocParser.php
src/Util/RegexHelper.php
tests/unit/CursorTest.php

See https://github.com/jgm/commonmark.js/compare/0.21.0...0.22.0 and #172
We'll need to check which of these changes should be ported into here:

[WIP] Spec 0.22

---

CHANGELOG.md
bin/commonmark
composer.json
tests/functional/BinTest.php

Add `./bin/commonmark` for converting Markdown at the command line

---

command-line.md
configuration.md

Per https://github.com/thephpleague/commonmark/pull/135#issuecomment-145123037

Add documentation for emphasis configuration

---

CHANGELOG.md
src/Inline/Parser/EntityParser.php
src/Util/RegexHelper.php
tests/functional/data/entities.html
tests/functional/data/entities.md

Fix entity parsing issues

---

composer.json

Resolves: https://github.com/thephpleague/commonmark/issues/89

Remove phpunit-mock-objects version constraint

---

src/Block/Element/ListItem.php

Fix logic bug with blank line after empty list item

---

.travis.yml

Mirrors https://github.com/thephpleague/skeleton/pull/79

Prefer dist + cache for Travis builds

---

tests/unit/Block/Renderer/HtmlBlockRendererTest.php
tests/unit/Inline/Renderer/HtmlInlineRendererTest.php

While having a look I noticed some tests could be useful, especially if this behavior might change later.

Add tests for the safe mode

---

src/Environment.php
tests/unit/EnvironmentTest.php

Allow inline parsers matching regex delimiter to be created

---

CHANGELOG.md
UPGRADE.md
src/Block/Element/AbstractBlock.php
src/Block/Element/BlockQuote.php
src/Block/Element/FencedCode.php
src/Block/Element/IndentedCode.php
src/Block/Element/ListItem.php
src/Block/Element/Paragraph.php
src/Block/Parser/ATXHeadingParser.php
src/Block/Parser/BlockQuoteParser.php
src/Block/Parser/FencedCodeParser.php
src/Block/Parser/HtmlBlockParser.php
src/Block/Parser/ListParser.php
src/Block/Parser/SetExtHeadingParser.php
src/Block/Parser/ThematicBreakParser.php
src/Cursor.php
src/CursorState.php
src/DocParser.php
src/Inline/Parser/CloseBracketParser.php
src/ReferenceParser.php
tests/unit/CursorTest.php

Fix/deprecate/rename the "FirstNonSpace" methods

---

.travis.yml

PHP 7.2 now available via Travis

---

index.md

fixed link to CommonMark JS reference implementation

fixed broken link

---

src/Block/Renderer/ParagraphRenderer.php
src/Inline/Parser/CloseBracketParser.php
src/Inline/Renderer/NewlineRenderer.php
src/Util/Html5Entities.php

I've removed the `else`s when we have already returned something :put_litter_in_its_place:

Clean elses

---

CHANGELOG.md
src/DocParser.php
src/Environment.php
src/Node/Node.php
tests/functional/MaximumNestingLevelTest.php

This implements #243 for blocks

Implement new max_nesting_level setting (#243)

---

README.md

Both of these projects are merging. See https://www.drupal.org/project/markdown/issues/2952435

Solidify official Drupal integration project

---

tests/benchmark/benchmark.php

* improvements to output of benchmark script
* add krakjoe/cmark (without hard dep)

benchmark things

---

tests/benchmark/benchmark.php

* selectively benchmark parsers
* optional process isolation
* set markdown source from cmdline
* set iterations from cmdline
* allow reading markdown from stdin
Maybe update readme also ...

more benchmark improvements

---

tests/benchmark/benchmark.php

* improve usage errors
* optionally collect memory usage stats from isolated processes
I think I'm done now ... sorry about noise ...

memory usage

---

tests/benchmark/benchmark.php

* csv output for  graphs
* improve isolation a little
`php benchmark.php -csv benchmark.csv`
This will do the normal test, but also write the results to the given csv file, for whatever you like ...
Supporting file descriptors means we can support piping the csv to another program, possibly gnuplot, but it's a mystery to me ...
[made with output csv](https://plot.ly/~krakjoe/3/)

add csv output for graphs

---

src/Block/Element/AbstractBlock.php
src/Block/Parser/FencedCodeParser.php
src/Context.php
src/ContextInterface.php
src/Cursor.php
src/DocParser.php
src/Inline/Element/AbstractInline.php
src/Inline/Parser/CloseBracketParser.php
src/UnmatchedBlockCloser.php
src/Util/LinkParserHelper.php
src/Util/RegexHelper.php

8.5% performance improvement per Blackfire:

Optimizations

---

README.md

**Affiliation disclosure:** I'm the author of `avensome/commonmark-bundle`  (Symfony 4 integration).
I'm not affiliated with `aptoma/twig-markdown`.

Update integrations in README

---

src/Block/Element/ListItem.php

Couldn't find any tests for ListItem, let me know if you want me to add tests for this

Add ListItem::getListData

---

.github/ISSUE_TEMPLATE/3_Security_issue.md

refs:
- d54b2f0af75409b7c7cb919a85e4ef7bc4275f61
cc:
- @colinodell

github template: fix heavy copy paste

---

CHANGELOG.md
composer.json
src/Block/Element/AbstractBlock.php
src/Block/Parser/FencedCodeParser.php
src/Block/Parser/ListParser.php
src/Block/Parser/SetExtHeadingParser.php
src/Cursor.php
src/Delimiter/DelimiterStack.php
src/Inline/Parser/BacktickParser.php
src/ReferenceParser.php
src/Util/LinkParserHelper.php
src/Util/RegexHelper.php

See https://github.com/commonmark/commonmark.js/compare/0.28.1...master

0.29 spec changes

---

.gitattributes
.ripstech/README.md
.ripstech/converter.php
.ripstech/link-rendering.php
.ripstech/xml-escape.php
.styleci.yml
.travis.yml
README.md

RIPS has graciously provided us with a complimentary license to scan this project for vulnerabilities!

Add RIPS security scanning

---

CHANGELOG.md
UPGRADE.md
docs/0.20/customization/document-processing.md
src/Block/Renderer/HtmlBlockRenderer.php
src/Delimiter/Processor/EmphasisDelimiterProcessor.php
src/Environment.php
src/Inline/Renderer/HtmlInlineRenderer.php
src/Inline/Renderer/ImageRenderer.php
src/Inline/Renderer/LinkRenderer.php
src/Util/Configuration.php
src/Util/ConfigurationAwareInterface.php
src/Util/ConfigurationInterface.php
tests/unit/Util/ConfigurationTest.php

Clean up the Configuration class; extract an interface; add a new set() method

Clean up the Configuration class

---

docs/0.18/customization/inline-rendering.md
docs/0.18/installation.md
docs/0.18/upgrading.md
docs/0.19/customization/inline-rendering.md
docs/0.19/installation.md
docs/0.19/upgrading.md
docs/1.0/configuration.md
docs/1.0/customization/event-dispatcher.md
docs/1.0/customization/inline-parsing.md
docs/1.0/customization/inline-rendering.md
docs/1.0/installation.md
docs/1.0/security.md

Improve docs

---

RELEASE_CHECKLIST.md
docs/1.0/basic-usage.md
docs/1.0/customization/block-parsing.md
docs/1.0/customization/block-rendering.md
docs/1.0/customization/cursor.md
docs/1.0/customization/environment.md
docs/1.0/customization/event-dispatcher.md
docs/1.0/customization/extensions.md
docs/1.0/customization/overview.md
docs/1.0/security.md

More documentation improvements

---

.travis.yml

NB `sudo` has defaulted to `false` for a while (even though they initially only defaulted it for new repos).

Test on PHP 7.4 stable

---

phpstan.neon.dist
src/Block/Element/FencedCode.php
src/Block/Parser/ATXHeadingParser.php
src/Cursor.php
src/DocParser.php
src/HtmlElement.php
src/Util/RegexHelper.php
src/Util/UrlEncoder.php

...of the last 8 months.
Please see [CI output](https://travis-ci.org/thephpleague/commonmark/jobs/620049465).

Unescaped pipe sign hid the errors

---

.travis.yml

Thank you @GrahamCampbell https://github.com/thephpleague/commonmark/pull/390#issuecomment-561327236
docs https://docs.travis-ci.com/user/environment-variables/#default-environment-variables

Do not run RIPS in PRs

---

CHANGELOG.md
phpstan.neon.dist
src/Block/Element/BlockQuote.php
src/Block/Parser/BlockQuoteParser.php
src/Block/Parser/FencedCodeParser.php
src/Cursor.php
src/Inline/Parser/BacktickParser.php
src/Inline/Parser/CloseBracketParser.php
src/Inline/Parser/EntityParser.php
src/Inline/Parser/EscapableParser.php
src/Inline/Parser/HtmlInlineParser.php
src/Inline/Parser/NewlineParser.php
src/Inline/Parser/OpenBracketParser.php
src/InlineParserEngine.php
src/Reference/ReferenceParser.php
src/Util/LinkParserHelper.php

This series of micro-optimizations reduces the parse time by 8% on PHP 7.4.

Micro-optimizations

---

src/Util/UrlEncoder.php
tests/unit/Util/UrlEncoderTest.php

Optimize URL normalization by immediately returning URLs with non-special chars as-is
Fixes #417

Optimize URL normalization

---

CHANGELOG.md
docs/1.4/upgrading.md
src/Environment.php
tests/unit/Environment/FakeBlock1.php
tests/unit/Environment/FakeBlock2.php
tests/unit/Environment/FakeBlock3.php
tests/unit/Environment/FakeInline1.php
tests/unit/Environment/FakeInline2.php
tests/unit/Environment/FakeInline3.php
tests/unit/EnvironmentTest.php

Resolve parent class

---

CHANGELOG.md
docs/1.4/upgrading.md
src/Block/Element/ListBlock.php
src/Block/Parser/ListParser.php
src/Block/Renderer/ListBlockRenderer.php
tests/unit/Block/Parser/ListParserTest.php
tests/unit/Block/Renderer/ListBlockRendererTest.php

These minor adjustments will better-align the constants with the CommonMark spec.

ListBlock constant changes

---

CHANGELOG.md
docs/1.5/extensions/autolinks.md
docs/1.5/extensions/mention.md
docs/1.5/extensions/overview.md
docs/1.5/upgrading.md
docs/_data/menu.yml
src/Extension/Autolink/InlineMentionParser.php
src/Extension/Mention/LinkGenerator/CallbackLinkGenerator.php
src/Extension/Mention/LinkGenerator/MentionLinkGeneratorInterface.php
src/Extension/Mention/LinkGenerator/StringTemplateLinkGenerator.php
src/Extension/Mention/MentionParser.php
tests/functional/Extension/Mention/MentionParserTest.php
tests/unit/Extension/Autolink/InlineMentionParserTest.php
tests/unit/Extension/Mention/LinkGenerator/CallbackLinkGeneratorTest.php
tests/unit/Extension/Mention/LinkGenerator/StringTemplateLinkGeneratorTest.php
tests/unit/Extension/Mention/MentionParserTest.php

Implement new MentionParser; deprecate the old one

---

src/Extension/Attributes/Event/AttributesListener.php
src/Extension/Attributes/Parser/AttributesBlockParser.php
src/Extension/Attributes/Parser/AttributesInlineParser.php
src/Extension/Attributes/Util/AttributesHelper.php
tests/unit/Extension/Attributes/Util/AttributesHelperTest.php

This will help simplify the changes we need to make for 2.0.

Move common attribute functionality into a helper class; add tests

---

README.md
docs/1.3/extensions/overview.md
docs/1.4/extensions/overview.md
docs/1.5/extensions/overview.md

Addresses the first task in #500.

Documentation updates

---

CHANGELOG.md
src/Extension/Footnote/Event/FixOrphanedFootnotesAndRefsListener.php
src/Extension/Footnote/FootnoteExtension.php
src/Extension/Footnote/Node/Footnote.php
src/Extension/Footnote/Node/FootnoteBackref.php
src/Extension/Footnote/Node/FootnoteRef.php
src/Extension/Footnote/Parser/AnonymousFootnoteRefParser.php
src/Extension/Footnote/Parser/FootnoteParser.php
src/Extension/Footnote/Parser/FootnoteRefParser.php
src/Extension/Footnote/Parser/FootnoteStartParser.php
src/Reference/ReferenceableInterface.php
tests/functional/Extension/Footnote/FootnoteSpecTest.php
tests/functional/Extension/Footnote/data/empty-footnote.html
tests/functional/Extension/Footnote/data/empty-footnote.md
tests/functional/Extension/Footnote/data/orphaned-footnote-ref.html
tests/functional/Extension/Footnote/data/orphaned-footnote-ref.md
tests/functional/Extension/Footnote/data/orphaned-footnote.html
tests/functional/Extension/Footnote/data/orphaned-footnote.md
tests/functional/Extension/Footnote/spec.txt

This PR adds a CommonMark-like spec for footnote behavior, which includes changes based on behavior found in other libraries supporting footnotes (like pandoc).

Footnote spec and related changes

---

.github/workflows/tests.yml

Same as https://github.com/thephpleague/commonmark/pull/515, but for the smaller number of tools that run on 1.5.

[1.5] Nice actions output

---

src/Extension/HeadingPermalink/HeadingPermalinkProcessor.php
src/Normalizer/UniqueSlugNormalizer.php
tests/functional/Extension/HeadingPermalink/HeadingPermalinkExtensionTest.php
tests/functional/Extension/TableOfContents/data/weird-relative.html
tests/unit/Normalizer/UniqueSlugNormalizerTest.php

Ensure generated heading permalinks are unique

---

CHANGELOG.md
docs/2.0/customization/abstract-syntax-tree.md
src/Node/Query.php
src/Node/Query/AndExpr.php
src/Node/Query/ExpressionInterface.php
src/Node/Query/OrExpr.php
tests/unit/Node/QueryTest.php

Implement Node query functionality

---

CHANGELOG.md
docs/2.0/upgrading/consumers.md
docs/2.0/upgrading/developers.md
docs/2.0/upgrading/integrators.md
src/Extension/Mention/MentionExtension.php
src/Extension/Mention/MentionParser.php
tests/functional/Extension/Mention/MentionExtensionTest.php

Rename 'mention/*/regex' option to '/mention/*/pattern'

---

docs/2.0/extensions/mentions.md

Fix 2.0 mention docs to use pattern instead of regex

---

docs/2.0/customization/delimiter-processing.md
docs/2.0/extensions/attributes.md
docs/2.0/upgrading/consumers.md

A few issues fixed up per #553. Missing punctuation, clarifying some example code, and adding output samples to some MD syntax.

Documentation changes

---

CHANGELOG.md
src/Extension/Table/TableParser.php
tests/functional/Extension/Table/data/single_column_table_and_block_elements.html
tests/functional/Extension/Table/data/single_column_table_and_block_elements.md
tests/functional/Extension/Table/data/table-and-block-elements.html
tests/functional/Extension/Table/data/table-and-block-elements.md
tests/functional/Extension/Table/data/table-in-list.html
tests/functional/Extension/Table/data/table-in-list.md

Fix parsing of tables within list items

---

CHANGELOG.md
docs/2.0/upgrading/consumers.md
docs/2.0/upgrading/developers.md
docs/2.0/upgrading/integrators.md
src/Extension/TableOfContents/TableOfContentsGenerator.php
src/Renderer/HtmlRenderer.php
tests/functional/Extension/TableOfContents/data/custom-class.html
tests/functional/Extension/TableOfContents/data/headings-with-inlines.html
tests/functional/Extension/TableOfContents/data/min-max.html
tests/functional/Extension/TableOfContents/data/position-before-headings.html
tests/functional/Extension/TableOfContents/data/position-placeholder-multiple.html
tests/functional/Extension/TableOfContents/data/position-top.html
tests/functional/Extension/TableOfContents/data/sample.html
tests/functional/Extension/TableOfContents/data/setext-headings.html
tests/functional/Extension/TableOfContents/data/style-bullet.html
tests/functional/Extension/TableOfContents/data/style-ordered.html
tests/functional/Extension/TableOfContents/data/weird-as-is.html
tests/functional/Extension/TableOfContents/data/weird-flattened.html
tests/functional/Extension/TableOfContents/data/weird-relative.html

Remove paragraph tags from ToC items

---

CHANGELOG.md
docs/2.0/extensions/default-attributes.md
docs/2.0/extensions/overview.md
src/Extension/Attributes/Util/AttributesHelper.php
src/Extension/DefaultAttributes/ApplyDefaultAttributesProcessor.php
src/Extension/DefaultAttributes/DefaultAttributesExtension.php
tests/functional/Extension/DefaultAttributes/DefaultAttributesExtensionTest.php

Implement new DefaultAttributesExtension

---

CHANGELOG.md
docs/2.0/customization/block-parsing.md
src/Extension/CommonMark/Parser/Block/HeadingParser.php
src/Extension/Table/TableParser.php
src/Parser/Block/AbstractBlockContinueParser.php
src/Parser/Block/BlockContinueParserInterface.php
src/Parser/Block/BlockContinueParserWithInlinesInterface.php
src/Parser/Block/ParagraphParser.php
src/Parser/MarkdownParser.php

This provides a slight (~5%) performance boost

Optimize block parsing

---

CHANGELOG.md
docs/2.0/extensions/description-lists.md
docs/2.0/extensions/overview.md
src/Extension/CommonMark/Node/Block/ListBlock.php
src/Extension/DescriptionList/DescriptionListExtension.php
src/Extension/DescriptionList/Event/ConsecutiveDescriptionListMerger.php
src/Extension/DescriptionList/Event/LooseDescriptionHandler.php
src/Extension/DescriptionList/Node/Description.php
src/Extension/DescriptionList/Node/DescriptionList.php
src/Extension/DescriptionList/Node/DescriptionTerm.php
src/Extension/DescriptionList/Parser/DescriptionContinueParser.php
src/Extension/DescriptionList/Parser/DescriptionListContinueParser.php
src/Extension/DescriptionList/Parser/DescriptionStartParser.php
src/Extension/DescriptionList/Parser/DescriptionTermContinueParser.php
src/Extension/DescriptionList/Renderer/DescriptionListRenderer.php
src/Extension/DescriptionList/Renderer/DescriptionRenderer.php
src/Extension/DescriptionList/Renderer/DescriptionTermRenderer.php
src/Node/Block/TightBlockInterface.php
src/Renderer/Block/ParagraphRenderer.php
tests/functional/Extension/DescriptionList/DescriptionListSpecTest.php
tests/functional/Extension/DescriptionList/spec.txt
tests/unit/Extension/DescriptionList/Node/DescriptionTest.php
tests/unit/Extension/DescriptionList/Renderer/DescriptionListRendererTest.php
tests/unit/Extension/DescriptionList/Renderer/DescriptionRendererTest.php
tests/unit/Extension/DescriptionList/Renderer/DescriptionTermRendererTest.php

Description list extension

---

.github/stale.yml

Add "do not close" label to stale exemption list

---

CHANGELOG.md
docs/2.0/customization/abstract-syntax-tree.md
docs/2.0/upgrading/developers.md
src/Extension/Attributes/Event/AttributesListener.php
src/Extension/DefaultAttributes/ApplyDefaultAttributesProcessor.php
src/Extension/ExternalLink/ExternalLinkProcessor.php
src/Extension/Footnote/Event/AnonymousFootnotesListener.php
src/Extension/Footnote/Event/FixOrphanedFootnotesAndRefsListener.php
src/Extension/Footnote/Event/GatherFootnotesListener.php
src/Extension/Footnote/Event/NumberFootnotesListener.php
src/Extension/HeadingPermalink/HeadingPermalinkProcessor.php
src/Extension/TableOfContents/TableOfContentsBuilder.php
src/Extension/TableOfContents/TableOfContentsGenerator.php
src/Node/Node.php
src/Node/NodeIterator.php
src/Node/Query.php
src/Node/StringContainerHelper.php
tests/unit/Node/NodeIteratorTest.php
tests/unit/Node/QueryTest.php

Implements the new node iterator described in #683 
Closes #683

Node Iterator

---

CHANGELOG.md
src/Extension/CommonMark/Parser/Inline/CloseBracketParser.php
tests/functional/Extension/Autolink/EmailAutolinkParserTest.php
tests/functional/Extension/Autolink/UrlAutolinkParserTest.php

Fix autolinks being incorrectly nested inside of links

---

.github/workflows/tests.yml

Test against PHP 8.1

---

.github/workflows/tests.yml
CHANGELOG.md
docs/2.0/extensions/front-matter.md
src/Extension/FrontMatter/Data/LibYamlFrontMatterParser.php
src/Extension/FrontMatter/FrontMatterExtension.php
tests/functional/Extension/FrontMatterExtension/FrontMatterExtensionTest.php

Add alternative to `symfony/yaml` with YAML extension.
https://www.php.net/manual/book.yaml.php

Support of YAML extension for front matter extension

---

docs/homepage.css

Have a look at this suggestion and see if you like it. I'm happy to change it so that it uses fixed sizes for different media queries if you prefer.

Added viewport relative font-size for heading h1.

---

CHANGELOG.md
composer.json

https://symfony.com/blog/symfony-6-0-0-beta1-released

Test against symfony/yaml 6.0

---

CHANGELOG.md
src/Extension/Autolink/UrlAutolinkParser.php
tests/functional/Extension/Autolink/UrlAutolinkParserTest.php

Fix AutolinkExtension not ignoring trailing strikethrough syntax

---

docs/2.3/extensions/autolinks.md

Fix mentions link

---

CHANGELOG.md
src/Extension/Footnote/Parser/FootnoteParser.php
tests/functional/Extension/Footnote/md/long.html
tests/functional/Extension/Footnote/md/long.md

Fix tab-indented footnote parsing

---

CHANGELOG.md
src/Extension/Embed/EmbedExtension.php
src/Extension/Embed/EmbedProcessor.php
src/Extension/Embed/EmbedStartParser.php
tests/functional/Extension/Embed/EmbedExtensionTest.php
tests/functional/Extension/Embed/data/after_list_regression.html
tests/functional/Extension/Embed/data/after_list_regression.md
tests/functional/Extension/Embed/data/embeds-with-autolinks-enabled.html
tests/functional/Extension/Embed/data/embeds-with-autolinks-enabled.md

Fix embed parsing

---

.github/workflows/tests.yml
composer.json

Bump test deps and test on PHP 8.2

Bump test dependencies

---

CHANGELOG.md
src/Parser/InlineParserEngine.php
tests/unit/Parser/InlineParserEngineTest.php

Fix InlineParserEngine error when no inline parsers are set

---

CHANGELOG.md
src/Extension/TaskList/TaskListItemMarkerRenderer.php

Fix missing HTML attributes

---

docs/2.4/customization/disabling-features.md
docs/_data/menu.yml

This is a common question that we should address in our documentation.
See #982, #907, and #648.

Add docs page about disabling features

---

.github/workflows/tests.yml

* Test against php 8.3
* Test against php 8.2 in stable mode

Test against php 8.2 and 8.3

---

CHANGELOG.md
src/Extension/SmartPunct/QuoteParser.php
tests/functional/Extension/SmartPunct/SmartPunctFunctionalTest.php

Don't change already-formatted quotation marks

---

CHANGELOG.md
composer.json
src/Util/RegexHelper.php
tests/functional/CMarkRegressionTest.php

Changed based on https://github.com/commonmark/commonmark.js/compare/0.31.0...0.31.1

commonmark 0.31.1 compatibility

---

docs/2.5/extensions/footnotes.md

The current example didn't contain a footnote to test. Anyone copying and pasting the example would have been confused (I know I was!)

Footnote documentation - add example

---

docs/2.7/index.md

This fixes the badge link to the license that is available in the root directory.

Fix license badge link
